### PR TITLE
Update to v1.12

### PR DESCRIPTION
**Pull request by matthewtiscareno**
v1.12.0.0  2023-04-18
        - Update steward name from Mitchell Gordon to Matthew Tiscareno
        - Improved definitions of epoch_reprojection_basis_utc, corotating_ring_longitude, minimum_corotating_ring_longitude, 
          and maximum_corotating_ring_longitude.  
        - Fixed typo in corotating_flag enumerated value definition. 
        - Regularized spelling of "corotation"
        - Add inertial_ring_longitude, minimum_inertial_ring_longitude, and maximum_inertial_ring_longitude.  These replace 
          ring_longitude, minimum_ring_longitude, and maximum_ring_longitude, which should be deprecated. 
        - Also, classes that are copied here from the Geometry and Display dictionaries should be deprecated, as of now.
          These include Body_Ident_Base, Reference_Frame_Ident, Central_Body_Ident, and Display_Direction. 
        - Actual deprecation not yet implemented.

### CODE REVIEW

**Comment by matthewtiscareno** [comment]
@jordanpadams:  If it is too late for this pull request to be included in the current build, then I understand.

**Comment by matthewtiscareno** [comment]
@jordanpadams:  We want to deprecate several classes and attributes, and I do not know the best practice for deprecating.  See PR description for details.  The need for advice on this point is the reason for my delay that is causing me to possibly miss the deadline.  If you are able to offer guidance, that would be great.

**Comment by matthewtiscareno** [comment]
The current version adds the new things we want to add, without deprecating the old things.  There are few enough data providers using this LDD that we can probably live with this for six months, if needed.

**Comment by matthewtiscareno** [comment]
Fixes [#241](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues/241), [#243](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues/243), [#244](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues/244), and [#245](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues/245). 

Does not fix [#242](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues/242), because deprecation not implemented.

**Comment by jordanpadams** [comment]
@matthewtiscareno we are working on updating the script to tag the releases in by end of day. if this looks good, you can go ahead with a merge and we will make sure it is included

**Comment by jordanpadams** [comment]
> @jordanpadams: We want to deprecate several classes and attributes, and I do not know the best practice for deprecating. See PR description for details. The need for advice on this point is the reason for my delay that is causing me to possibly miss the deadline. If you are able to offer guidance, that would be great.

@matthewtiscareno per this, at this time, I do not believe we have a way to "deprecate" classes or attributes other than just removing them and major versioning your LDD (since it is not backwards compatible). I will ping @jshughes to see if there is a way to do this.

**Comment by matthewtiscareno** [comment]
> > @jordanpadams: We want to deprecate several classes and attributes, and I do not know the best practice for deprecating. See PR description for details. The need for advice on this point is the reason for my delay that is causing me to possibly miss the deadline. If you are able to offer guidance, that would be great.
> 
> @matthewtiscareno per this, at this time, I do not believe we have a way to "deprecate" classes or attributes other than just removing them and major versioning your LDD (since it is not backwards compatible). I will ping @jshughes to see if there is a way to do this.

In that case, I think it's best to go with the current version for this build.  We'll consider removing items and incrementing to v2.0 in the next build.

**Review by mace-space — APPROVED** [review]
Looks good

**Comment by jshughes** [comment]
@jordanpadams @matthewtiscareno Currently there is no capability to deprecate classes or attributes in LDDs as there is for the Common dictionary. The assumption was made early on that the definitions would simply be removed. A kludge would be to hard code the deprecated item identifiers into LDDTool. I only mention this in case a temp solution is necessary. Adding deprecation to LDDs is probably a DDWG discussion topic.

**Comment by matthewtiscareno** [comment]
> @jordanpadams @matthewtiscareno Currently there is no capability to deprecate classes or attributes in LDDs as there is for the Common dictionary. The assumption was made early on that the definitions would simply be removed. A kludge would be to hard code the deprecated item identifiers into LDDTool. I only mention this in case a temp solution is necessary. Adding deprecation to LDDs is probably a DDWG discussion topic.

Thank you for the helpful perspective, @jshughes.  It seems everyone agrees that deprecated material should simply be removed and a major version number incremented.  We'll consider this for next build.

**Comment by matthewtiscareno** [comment]
> Fixes [#241](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues/241), [#243](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues/243), [#244](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues/244), and [#245](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues/245).
> 
> Does not fix [#242](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues/242), because deprecation not implemented.

I was over-enthusiastic in saying this.  Some of these are still to do.

**Pull request merged**
